name: ml_s21
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyterlab
  - pandas
  - matplotlib
  - numpy
  - seaborn
  - scipy
  - kaggle
  - scikit-learn
  - lightgbm
  - statsmodels